### ISSUE TITLE
Unitless shorthands

### ISSUE THREAD

**Issue by kitten** [styled-components/css-to-react-native#40]
So on SC we've seen some complaints about properties being able to be unitless, e.g. `padding-top: 2`, but not shorthands: `padding: 2px`.

This probably comes from the difference here: https://github.com/styled-components/css-to-react-native/blob/master/src/index.js#L8

And here: https://github.com/styled-components/css-to-react-native/blob/master/src/tokenTypes.js#L31

Since most directions don't expect unitless numbers: https://github.com/styled-components/css-to-react-native/blob/master/src/transforms/util.js#L6

The question is, since this seems like an inconsistency, do we want to change this? :)

cc @mxstbr @jacobp100

**Comment by jacobp100** [comment]
It's sort of difficult because if we do this, we essentially create a whitelist of properties. It just means if RN adds new styles anywhere, we have to keep up-to-date.

**Comment by chinesedfan** [comment]
@jacobp100 Maybe there is really no elegant way to implement it. But this project is called "css-to-**react-native**", it is normal to include some logics that should always follow RN's steps. 

cc @mxstbr.

**Comment by yordis** [comment]
I am not sure if this is the right thread because the one was closed on SC.

If you see SC as a styling engine that provides you the `theme + style parser` (no css parser) and you would have something like `react-dom` and `react-native` which specific parser will do their job (yes it does it right now to some level but once you merge web with mobile then the specially cases will start coming out, like this one)

Probably most of us are Web developers and it makes sense for us to add units but for people coding on RN (I started a couple of weeks ago but include me) having units just add complexity to what they are used already. You can't migration your objects because now you need to pay attention to add units, and the worst case `if I am not mistaking` is that no all the time applies the logic of adding units ...

The idea of copying css and hand free makes no sense at all because you can't port `px` values to the mobile because there is no `px` unit, so probably everywhere you add `px` you will have to modifier the values because the calculation is off completely so I dont see the benefits (`em` could work but still there is no relative to the last font size either)

I would push to remove complexity to RN people and remove units.

P.S: Perspective on removing complexity or not is more fundamentally based on personal opinions but I would take more feedbacks from RN engineers like @iRoachie . This is my first time working full-time on RN and I can tell you, this add complexity for me right now, now I need to memories when tu use `px` or not (no including that RN community will no get why I am putting `px` in my code and they will no support people using SC because fundamentally is different from the RN Style engine).

**Comment by yordis** [comment]
@philpl any update on what will be the move of styled-components and unitless situation?

**Comment by jacobp100** [comment]
Currently you can remove units unless you use CSS shorthands. There are no plans to remove units in shorthands, and this is unlikely to change.

You can look at the discussions when this changed for reasons why we switched to enforcing units.

**Comment by yordis** [comment]
@jacobp100 which discussions?

**Comment by jacobp100** [comment]
A thought, maybe we could just `console.warn` on dev when you miss required units. It might reduce bugs for end users when they refactor their CSS.

For the discussion on why we changed from unitless to units is on #20. Sorry about the late response!

**Comment by probablyup** [comment]
This is still being flagged in issues against s-c, would love to see some movement either way on this. A few potential solutions:

1. As @jacobp100 suggested, warn.
2. Allow all properties to be unitless and add a unit behind the scenes if needed.
3. warn & throw out CSS rules without units where there should be a unit (this actually probably wouldn't be too arduous since there are few CSS properties that legitimately don't have units)

**Comment by jacobp100** [comment]
I do mean to get round to adding warnings, it's just finding time. I had a very-POC PR for how I think it could work

**Comment by dgobaud** [comment]
Curious why does it not make sense to remove units from shorthands? I don't understand the reasoning. Whitelist is mentioned so shorthands can be made up so the problem is by default units are expected and you would have to whitelist shorthands that don't require the units and that is the problem?

Couldn't there be a list of standard shorthands like margin that don't need the unit?

**Comment by jacobp100** [comment]
@dgobaud You can read some of the reasoning over at #20. There's also linked issues in there, and probably linked issues in the linked issues. I don't really want to reopen the discussions on this, it seems pretty settled - units are here to stay! But I'm happy to answer any questions on bugs etc. 🙂

**Comment by dgobaud** [comment]
@jacobp100 interesting so it seems the CSS spec says pixels are not physical device pixels - meaning unitless like the RN units? I guess this means the correct thing to do is actually use px everywhere?

**Comment by jacobp100** [comment]
Not too sure what you mean, but yeah, pixels on the web behave the same way as RN

**Comment by GollyJer** [comment]
Hi. I ran into this the other day and [wasted some brain cycles](https://github.com/styled-components/styled-components/issues/2882) trying to figure out what was going on. 😃

Are there any other units that can be used besides `px`? If not, maybe the warning should be more explicit?
`"px" is now required for all css measurements.`
and maybe point to the fact that `px` is density independent? https://www.w3.org/TR/css3-values/#px

It's a little bit confusing of a change.

**Comment by likern** [comment]
I have the problem with that. I created custom Text components, which overrides Text, considering **lineHeight** as relative value, not absolute. So `line-height: 1.5` instead of `line-height: 18px`. In that case I don't have units. And I get this warning.

**Comment by jacobp100** [comment]
@likern My understanding was that line height is _always_ a length value in React Native, never a multiplier. Correct me if I'm wrong. But if that is the case, I'm glad these warnings helped highlight that! :smile:

**Comment by likern** [comment]
> length value

Yes, it was. That's why I've decided to create wrapper which uses it as multiplier. As far as I know it is a recomended approach in CSS. And anyway designers use multipliers in tools like Figma.

I couldn't imagine omitting `px` postfix could lead to some errors in debug mode. Now it's a blocker for me.

**Comment by jacobp100** [comment]
The aim of this library is to transform bit of CSS that works on both web and React Native. Because this isn't natively supported in RN, I wouldn't feel comfortable loosening the rules here

But if you give me details on your wrapper, I'd be happy to look at how you could get it to work. We have a few libraries that do this kind of pre-processing before handing off here, so it seems very do-able

**Comment by likern** [comment]
My component is very simple. It just wraps RN Text component. It is expected to be working after css-to-react-native strips units off.

So I get usual **lineHeight** as number, but just treat it as multiplier (instead of absolute value in pixels) - and pass to RN Text `lineHeight = fontSize * lineHeight`.
I shared my component here: https://gist.github.com/likern/6e2da0bbe21fd0a7f7b4255d4537eb6e

**Comment by jacobp100** [comment]
Okay, makes sense. You’re actually the first person I’ve seen to do this via a wrapper component - most people just wrap the `styled` function in some way

Since your component requires the font size to be present anyway, you could do this via a mixin in styled components

We have previously been too loose in what we accept, and this has caused issues for parsing. We are fixing these issues and making the parser stricter, and this does have the consequence that people using those behaviours will no longer be able to do so. I think the warnings are important so we can guide people away from writing stuff that can cause bugs

**Comment by likern** [comment]
@jacobp100 I don't have access to `styled` because I'm using `css` prop transformation, so my code looks like this:
```js
<CustomText
    css={`
        font-family: Gilroy-SemiBold;
        font-size: 28px;
        line-height: 20;
    `}
>
    This is a custom text component
 </CustomText>
```

The next where I can grab this information is inside custom component.

**Comment by likern** [comment]
What about adding **styled.config.js** file which will allow to add custom code transformations at build-time, while keeping core css-to-react-native untouched?

**styled.config.js:**
```js
module.exports = {
  "react-native": {
    extends: {
      file: "js file with compile-time transformations using babel-plugin-preval "
    }
  }
};
```
Developers can write their own transformations using **babel-plugin-preval**.

**In my example:**

```js
<CustomText
    css={`
        font-family: Gilroy-SemiBold;
        font-size: 28px;
        line-height: 1.5;
    `}
>
    This is a custom text component
</CustomText>
```
will be transformed by my own transformation (it is a user responsibility) (which will be called by css-to-react-native at **pre-execution** phase) to

```js
<CustomText
    css={`
        font-family: Gilroy-SemiBold;
        font-size: 28px;
        line-height: 42px;
    `}
>
    This is a custom text component
</CustomText>
```

Then the core strict logic of css-to-react-native will be applied.

**Comment by jacobp100** [comment]
I meant like this,

```js
const fontSize = (fontSize, lineHeightMultiplier) => `
  font-size: ${fontSize}px;
  line-height: ${fontSize * lineHeightMultiplier}px;
`;

<NormalText
    css={`
        font-family: Gilroy-SemiBold;
        ${fontSize(25, 1.5)}
    `}
>
    This is a normal text component
</NormalText>
```

Your babel plugin idea will probably work too!

Btw, we used to actually transform unitless line heights for the case,

```css
font: 16px/1.5 "Some font"
```

And that used to give a line height of 24px. But we removed it because it does not work for the case,

```js
const BaseText = styled`
  font: 16px/1.5 "Some font";
`

const BiggerText = styled`
  font-size: 32px;
`

<BaseText>
  My line height is correct
  <BiggerText>
    But mine is not
  </BiggerText>
</BaseText>
```

**Comment by felippepuhle** [comment]
So, I have an app with hundreds/thousand of components and now it's required to use units even though react native itself doesn't require that? What the heck?

**Comment by likern** [comment]
> So, I have an app with hundreds/thousand of components and now it's required to use units even though react native itself doesn't require that? What the heck?

You can use old style property passing object

**Comment by jacobp100** [comment]
@felippepuhle there’s a code mod available!

**Comment by fontesrp** [comment]
> @felippepuhle there’s a code mod available!

I'm in the same situation as @felippepuhle. Is there any way to silence the warnings? Not sure what code mod means...

**Comment by likern** [comment]
> > @felippepuhle there’s a code mod available!
> 
> I'm in the same situation as @felippepuhle. Is there any way to silence the warnings? Not sure what code mod means...

https://github.com/facebook/codemod

**Comment by fontesrp** [comment]
You mean I have to refactor the entire project to add `px` to every style prop?

That's insane...

I guess I just found some work to do for the following weeks

**Comment by jacobp100** [comment]
@fontesrp if you look in the team repos, there is a project that will add the px to all the lines for you

**Comment by felippepuhle** [comment]
I know about the codemod, I just commented yesterday 'cause I don't think it's a wise decision change the default behavior.

Sorry if I was rude.

Thanks!

**Comment by jacobp100** [comment]
Don’t worry, you didn’t come off as rude! It’s something we’ve wanted to do for a while to make the parsing more reliable. There’s a few posts around here if you wanted to read about the issues with how it was before

**Comment by AllyssonAlas** [comment]
There's a waning in elevation property for android, it claims that elevation should be unitless but even if you dont put anything, it is still transformed to px. 

react-native: 0.61.2
styled-components:  ^5.0.0

my code: 

```
import {Dimensions} from 'react-native'
import styled from 'styled-components/native'
import {css} from 'styled-components'

const {height, width} = Dimensions.get('window')

export const Container = styled.TouchableOpacity`
   align-items: center;
   background-color: rgba(246, 130, 13, 1);
   ${props => props.toCancel && css`background-color: rgba(255, 0, 0, 1)`};
   ${props => props.toConfirm && css`background-color: rgba(25, 184, 14, 1)`};
   border-radius: 10px;
   elevation: 7;
   height: ${props => props.secondaryButton ? `${height * 0.09}px` : `${height * 0.1}px`};
   justify-content: center;
   width: ${props => props.secondaryButton ? `${width * 0.45}px` : `${width * 0.85}px`};
`
```

The warning:
![83184012_1569687023155643_4845915899615510528_n](https://user-images.githubusercontent.com/47720717/72754336-46ffca80-3ba6-11ea-91e9-cb416a62bd68.png)

**Comment by jacobp100** [comment]
@AllyssonAlas I think the warning message you got is for some other code. The value printed in the warning message is verbatim - it didn't add the `px` itself. Somewhere, there will be an `elevation: 7px`

**Comment by AllyssonAlas** [comment]
@jacobp100 You're right, I've found another component with ``` elevation: 7px ```, removed and the app stopped showing the warning, React Native lint keep showing an error in elevation properties, do you know how to solve this error?
![captura](https://user-images.githubusercontent.com/47720717/72757983-36ece880-3bb0-11ea-84a2-80104e56a992.PNG)

**Comment by jacobp100** [comment]
Sorry, I don't know what's causing that issue. If it's a package, feel free to link it here and I can take a look

**Comment by AllyssonAlas** [comment]
@jacobp100 Thank you anyway, I'll search the resolution and if I find something, I shall publish here.

**Comment by Rodrigo816** [comment]
This lacks consistency
look at the exemple above

```
export const Input = styled(FormikInput).attrs({
  containerStyle: {
    font-Size: props => props.theme.typography.size_large
  },
  errorStyle: {
  },
})`
```

on theme
`  size_large: 18`

**gives this error: expected styles to contain units**

if I make this
`  size_large: '18px'`

**react native crashes string cannot be cast to java.lang.double**

Any ideas?

**Comment by jacobp100** [comment]
I think your error is coming from some other code not shown in the example. You probably somewhere have,

```
styled.Text`
  font-size: ${props => props.theme.typography.size_large};
`
```

Generally, should store `size_large` as a number, then change the above to

```
styled.Text`
  font-size: ${props => props.theme.typography.size_large}px;
`
```

(Notice the px)

Hope this helps!

**Comment by olehs** [comment]
@jacobp100 , can the same be done with object-like styles? I.e

**Comment by sibelius** [comment]
can we have a stylelint for this?

https://stylelint.io/

**Comment by sibelius** [comment]
what is the codemod that adds units?

**Comment by sibelius** [comment]
codemod here https://github.com/styled-components/styled-components-native-code-mod

fix to work with latest styled-components version https://github.com/styled-components/styled-components-native-code-mod/pull/21

**Comment by mstarcevic** [comment]
I'm using both styled-components and styled-system with typescript. I have found that if you make use of the default parms, you can use without units and there will not be any warnings pop up.

You can either include everything with the defaults or mix as you like. For the styles that are entered with the defaults, the format is as per RN but for the styles within the styled-component proper, it is the normal hyphenated naming.

A sample of my working code...

interface ICustomProps extends BorderProps, FlexboxProps, LayoutProps, SpaceProps {}; 

export const LineItem = styled.View<ICustomProps>``;

LineItem.defaultProps = {
    width: "98%",
    flexDirection: "row",
    borderColor: "black",
    marginTop: 5,
    marginBottom: 5,
    marginLeft: 16,
    borderBottomWidth: 1,
    paddingTop: 8,
    paddingBottom: 5,
    paddingLeft: 10,
}

export const HeaderItem = styled(LineItem)`
    background-color: #f5f5f5;
`;

HeaderItem.defaultProps = {
    //backgroundColor: "#f5f5f5",
    borderTopWidth: 1
}

**Comment by wtfluckey** [comment]
What is the status on this? Other issues are being [closed](https://github.com/styled-components/css-to-react-native/issues/129) and linking to this one, but there is no indication on whether or not this idea is dead or still being considered?

**Comment by jacobp100** [comment]
It's not being considered. I wanted to keep this open for visibility, but it's probably had its time now.

Hope this clarifies things
